config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 resources :users
 resources :sessions
 root 'users#landing'
 get 'landing',to:'users#landing',as:'landing'
 get 'signup', to:'users#new',as:'signup'
 post 'register', to:'users#create',as:'register'
 get 'signin', to:'sessions#new', as:'signin'
 post 'login', to:'sessions#create',as:'login'
 get 'logout', to:'sessions#destroy',as:'logout'
 get 'createPost', to:'root#create',as:'createPost'
 post '/add', to:'root#add',as:'add'
 delete '/delete/:id',to:"root#delete"
 get '/update/:id',to:"root#update"
 post '/updateform', to:"root#updateform"
 get '/error', to:'root#error'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence:true, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        if session[:user_id]
            @current_user||=User.find(session[:user_id])
        else 
            @current_user=nil
        end  
    end          
end

app/controllers/root_controller.rb
class RootController < ApplicationController

    def create
        @posts=Post.all
        render "createPost"
    end  
    
    def add
       @post=Post.new()
       @post.title=params[:title]
       @post.description=params[:description]
       @post.emailId=User.find(session[:user_id]).email
       @post.save
       @posts=Post.all
       @response={
           :add=>true
       }
       redirect_to('/createPost')
    end   
    
    def displayAll
        @posts=Post.all
        render "displayAll"
    end 
    
    def delete
        @post=Post.find(params[:id])
        @post.destroy
        @posts=Post.all
        redirect_to('/createPost')
    end 
    
    def update
        if(session[:user_id]!=nil)
            @post=Post.find(params[:id])
            @id=params[:id]
            @title=@post.title
            @description=@post.description
            render "update"
        else
            redirect_to('/error')
        end  
    end      

    def updateform
            @post=Post.find(params[:id])
            @post.title=params[:title]
            @post.description=params[:description]
            @post.save
            @post=Post.all
            redirect_to('/createPost')
    end    

    def error
        render "error"
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end    

    def create
        email=params[:username]
        password=params[:userpassword]
        user=User.find_by(:email=>email)
        if user && user.password_digest==password
            response={
                :loggedIn=>true 
            }
            session[:user_id]=user.id
            redirect_to('/landing')
           
        else
            @loggedIn=false   
            render "new"
        end  
    end    

    def destroy
        session[:user_id]=nil
        redirect_to landing_path
    end    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        render "new"
    end    

    def create
        email=params[:username]
        password=params[:userpassword]
        user=User.find_by(:email=>email)
        if user
            @register=false
            render "new"
        else
            newUser=User.new();
            newUser.email=email;
            newUser.password_digest=password;
            newUser.save
            @register=true
            render "new"
        end    
    end    

    def destroy
    end   
    
    def landing
        @posts=Post.all
        render "layouts/landing"
    end    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElitmusProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  </head>

  <body style="background-image:url('https://files.123freevectors.com/wp-content/original/133714-green-yellow-and-white-abstract-background-vector.jpg'); no-repeat;background-size:cover">
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/landing.html.erb
<%if current_user%>
    <h5 style="float:right">Hello <%=current_user.email%></h5>
    <a href="<%=logout_path%>" class="btn btn-primary" style="float:left;margin:1%;">Logout</a>
    <a href="/createPost" class="btn btn-primary" style="float:left; margin:1%;">Create/Edit Posts</a>
    <% if @posts!=nil%>
    <%@posts.each do |post|%>
        <div style="display:inline-block;justify-content:space-around;margin-top:5%">
        <div class="card" style="width: 18rem;margin:10%">
        <div class="card-body">
        <h5 class="card-title"> <%=post.title%></h5>
        <p class="card-text"><%=post.description%></p>
        </div>
        </div>
        </div>
        <%end%>
    <%end%>    
<%else%>

<div style="display:flex;justify-content:center;margin-top:15%">
    <a href="<%=signup_path%>" class="btn btn-primary" style="margin:5%;min-width:200px">Signup</a>
    <a href="<%=signin_path%>" class="btn btn-primary" style="margin:5%;min-width:200px">Login</a>
</div> 


<%end%>

app/views/root/createPost.html.erb
<%if session[:user_id]==nil%>
  <h2 style="display:flex;justify-content:center;margin:10%">No such page exits!!</h2>
<%else%>

<h5 style="display:flex;justify-content:center;margin:2%">Create new Advertisement</h5>
<a href="<%=logout_path%>" class="btn btn-primary" style="float:right;margin:2%;margin-top:-40px">Logout</a>
<form method="POST" action="/add">
<%=token_tag%>
<div class="col-md-6" style="margin:0 auto;">
<div class="mb-3">
  <label for="title" class="form-label">Title</label>
  <input type="text" class="form-control" id="title" name="title">
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <textarea class="form-control" id="description" name="description" rows="3"></textarea>
</div>
<input type="submit" class="btn btn-primary" value="Add Post">
</div>
</form>

<% if @posts!=nil%>
<%@posts.each do |post|%>
    <%if(post.emailId==User.find(session[:user_id]).email)%>
    <div style="display:inline-block;justify-content:space-around;margin-top:5%">
    <div class="card" style="width: 18rem;margin:10%">
    <div class="card-body">
    <h5 class="card-title"> <%=post.title%></h5>
    <p class="card-text"><%=post.description%></p>
    <a href="/update/<%=post.id%>" class="btn btn-primary">Edit</a>
    <a href="/delete/<%=post.id%>" data-method="delete" class="btn btn-danger">Delete</a>
    </div>
    </div>
    </div>
    <%end%>
    <%end%>
<%end%> 
<%end%>

app/views/root/error.html.erb
<h2 style="display:flex;justify-content:center;margin:10%">No such page exits!!</h2>

app/views/root/update.html.erb
<a href="<%=logout_path%>" class="btn btn-primary" style="float:right;margin:1%;">Logout</a>
<form method="POST" action="/updateform">
<input type="hidden" value=<%=@id%> name="id">
<%=token_tag%>
<div class="col-md-6" style="margin:0 auto;">
<div class="mb-3">
  <label for="title" class="form-label">Title</label>
  <input type="text" class="form-control" id="title" name="title" value=<%=@title%>>
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <textarea class="form-control" id="description" name="description" rows="3"><%=@description%></textarea>
</div>
<input type="submit" class="btn btn-primary" value="Update Post">
</div>
</form>

app/views/users/new.html.erb
<h1 style="display:flex;justify-content:center">Sign Up</h1>

<%if @register%>
  <h5>Account created successfully</h5>
  <a href="<%=signin_path%>">Login</a>

<%elsif @register!=nil%>
  <h5>Email is already taken</h5>  
<%end%>

<h4><%=@message%></h4>

<form method="POST" action="<%=register_path%>">
<%=token_tag%>
<div class="col-md-4" style="margin:auto">
  <div class="mb-3">
    <label for="username" class="form-label">Email</label>
    <input type="email" class="form-control" id="username" name="username" aria-describedby="emailHelp" required>
    <div id="emailHelp" class="form-text">We will never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="userpassword" class="form-label">Password</label>
    <input type="password" class="form-control" id="userpassword" name="userpassword" required>
  </div>
  
  <input type="submit" class="btn btn-primary" value="Register">
  </div>
</form>